In [1]:
import numpy as np


In [7]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

# Implement MAE

In [16]:
def mae(y_true, y_predicted):
    total_error = 0  # Corrected variable name
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error:", total_error)
    
    mae = total_error / len(y_true)
    return mae


mae_value = mae(y_true, y_predicted)
print("Mean Absolute Error:", mae_value)


Total error: 2.5
Mean Absolute Error: 0.5


In [17]:
np.mean(abs(mae(y_true, y_predicted)))

Total error: 2.5


0.5

In [18]:
np.sum(abs(mae(y_true, y_predicted)))

Total error: 2.5


0.5

# loss function

In [19]:
np.log([0.0000000000005])

array([-28.3241683])

In [27]:
epsilon = 1e-15



In [28]:
y_predicted

array([1, 1, 0, 0, 1])

In [29]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new 

[1, 1, 1e-15, 1e-15, 1]

In [30]:
y_predicted_new  = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new 

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [31]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [32]:
-np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1-y_predicted_new))

17.2696280766844

In [33]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new  = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1-y_predicted_new))



In [34]:
log_loss(y_true, y_predicted)

17.2696280766844